### ISSUE TITLE
SwiTAS Refuses to connect in controllers

### ISSUE THREAD

**Issue by armoar334** [TheGreatRambler/SwiTAS#12]
I Followed the readme Until connecting the controllers, at which point the SwiTAS program gets stuck in an endless loop of the "remove controllers" prompt. I have Tried:
- Rebooting the switch
- Restarting the program (causes switch to crash)
Edit: i should also add that the swiTAS controllers do not show up on the switch.

**Comment by redanaheim** [comment]
This is a known issue and I forget the fix (if you ask in Discord TGR will tell you) but please ask in the Discord before opening an issue.

**Comment by TheGreatRambler** [comment]
You have to make sure you only press change grip order when you have that dialog open, if you open it earlier you softlock the app and have to restart the sysmodule and the pc app.
