### ISSUE TITLE
Really hope this isn't dead!

### ISSUE THREAD

**Issue by jdroo** [TheGreatRambler/SwiTAS#15]
Dang, I got all excited that a tas tool existed for switch, installed it on my switch just to find out this tool does not work on newer firmware, such a shame, I really hope you update this!

**Comment by TheGreatRambler** [comment]
Sadly it would take an incredible amount of work to update this, and I've since moved on to other projects, sorry about that. Luckily there are still TAS tools using text files that support yuzu now, I would recommend looking into those
